config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :items, only: %i[index show new create] do
    resources :bookings, only: %i[create] do
      resources :payments, only: %i[new]
    end
  end

  get "/dashboard", to: "dashboard#main"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :bookings, dependent: :destroy

  validates :name, :description, :price_per_day, presence: true
  validates :description, length: { minimum: 5 }
  validates :name, uniqueness: { scope: :user, message: 'You already have this item listed' }
  validates :price_per_day, numericality: { less_than_or_equal_to: 10_000, greater_than: 1, only_integer: true }
  validates :image, presence: { message: 'must be provided' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        # For additional fields in app/views/devise/registrations/new.html.erb
        devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :username, :is_owner])

        # For additional in app/views/devise/registrations/edit.html.erb
        devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :username, :is_owner])
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @booking = Booking.new(booking_params)
    @booking.item = @item
    @booking.user = current_user
    number_of_days = (@booking.end_date - @booking.start_date).to_i
    @booking.total_price = (number_of_days * @item.price_per_day)
    if @booking.save
      price = Stripe::Price.create(
        {
          unit_amount: (@booking.total_price * 100).to_i,
          currency: 'eur',
          product_data: {
            name: @booking.item.name,
          }
        }
      )

      session = Stripe::Checkout::Session.create(
        {
          line_items: [
            {
              price: price.id,
              quantity: 1
            }
          ],
          mode: 'payment',
          success_url: dashboard_url,
          cancel_url: new_item_booking_payment_url(@item.id, @booking.id)
        }
      )

      @booking.update(stripe_session_id: session.id) # sla de sessie-ID op in de database, zodat je deze kunt gebruiken in de view
      redirect_to  new_item_booking_payment_path(@item, @booking) # redirect naar de checkout pagina voor deze boeking
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def main
    @items = Item.where(user: current_user)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @query = params[:query]
    if @query.present?
      @items = Item.where('name ILIKE ?', "%#{@query}")
    else
      "No results found"
    end
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price_per_day, :category_name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @booking = current_user.bookings.find(params[:booking_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/main.html.erb
<div class="container align-items-stretch pt-4">
  <div class="row">
    <div class="col-12 pt">
      <div class="header bg-light d-flex align-items-center justify-content-center">
        <div class="text-end">
          <h1 class="header-text">Dashboard</h1>
        </div>
      </div >
      <% if @query.present? %>
        <% if @items.any? %>
          <h2 class="text-start mt-4 mb-5"> Search results for "<%= @query %>"</h2>
        <% else %>
          <h2 class="text-start mt-4 mb-4">Sorry, nothing found</h2>
        <% end %>
      <% end %>
      <br>
      <div class="card d-flex justify-content-start">
        <h2>Your listed items</h2>
      </div>
      <div class="row">
        <% @items.each do |item| %>
          <div class="col-lg-4 col-md-6 mb-4">
            <%= link_to item_path(item), class: "text-decoration-none" do %>
              <div class="item-card">
                <div class="card-img" style="background-image: url('<%= cl_image_path item.image.key %>');"></div>
                <div class="card-info px-3">
                  <div class="d-flex justify-content-between">
                    <div class="text-start text-decoration-underline"><%= item.name %></div>
                    <div class="text-end text-decoration-underline">
                      <span style="font-weight: bold; font-size: 1.1em;"><%= humanized_money_with_symbol item.price_per_day %>/day</span>
                    </div>
                  </div>
                  <p>Category: <%= item.category_name%></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="card d-flex justify-content-start">
        <h2>Currently renting</h2>
      </div>
      <div class="row">
        <% @items.each do |item| %>
          <div class="col-lg-4 col-md-6 mb-4">
            <%= link_to item_path(item), class: "text-decoration-none" do %>
              <div class="item-card">
                <div class="card-img" style="background-image: url('<%= cl_image_path item.image.key %>');"></div>
                <div class="card-info px-3">
                  <div class="d-flex justify-content-between">
                    <div class="text-start text-decoration-underline"><%= item.name %></div>
                    <div class="text-end text-decoration-underline">
                      <span style="font-weight: bold; font-size: 1.1em;"><%= humanized_money_with_symbol item.price_per_day %>/day</span>
                    </div>
                  </div>
                  <p>Category: <%= item.category_name%></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container align-items-stretch pt-4">
  <div class="row">
    <div class="col-12 pt">
      <div class="header bg-light d-flex align-items-center justify-content-center">
        <div class="text-end">
          <h1 class="header-text">Catalogue</h1>
        </div>
      </div >
      <% if @query.present? %>
        <% if @items.any? %>
          <h2 class="text-start mt-4 mb-5">Search results for "<%= @query %>"</h2>
        <% else %>
          <h2 class="text-start mt-4 mb-4">Sorry, nothing found</h2>
        <% end %>
      <% end %>
      <br>
      <div class="row">
        <% @items.each do |item| %>
          <div class="col-lg-4 col-md-6 mb-4">
            <%= link_to item_path(item), class: "text-decoration-none" do %>
              <div class="item-card">
                <div class="card-img" style="background-image: url('<%= cl_image_path item.image.key %>');"></div>
                <div class="card-title px-3">
                  <div class="d-flex justify-content-between">
                    <div class="text-start text-decoration-underline"><%= item.name %></div>
                    <div class="text-end text-decoration-underline">
                      <span style="font-weight: bold; font-size: 1.1em;"><%= humanized_money_with_symbol item.price_per_day %>/day</span>
                    </div>
                  </div>
                  <div class="card-info d-flex justify-content-between">
                    <p><%= item.artist %></p>
                    <p><i><%= item.category_name %></i></p>
                  </div>
                </div>
                <div class="card-button">
                  <div class="primary-btn primary-hover mb-1">
                    Check availability
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="row justify-content-center">
  <div class="col-xl-5">
    <div class="card p-5">
      <div class="mb-1 d-flex justify-content-center">
        <h3>Upload a new item</h3>
      </div>
      <hr>
      <%= simple_form_for @item do |f| %>
        <%= f.input :name %>
        <%= f.input :description, hint: false %>
        <%= f.input :price_per_day %>
        <%= f.input :category_name, collection: ["Choose from list", "Modernism", "Impressionism", "Contemporary", "Photographs", "Sculptures"],
          label: "Select a category", disabled: ["Choose from list"], selected: "Choose from list", include_blank: false %>
        <%= f.input :image, as: :file, label: "Upload a photo of your item" %>
        <div class="d-flex justify-content-center mt-4">
          <%= f.submit class: "primary-btn full-width-btn" %>
        </div>
        <div class="d-flex justify-content-center mt-2">
          <%= link_to "Back", items_path, class: "secondary-btn full-width-btn"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="pet-show-container container my-5">
  <div class="row">
    <div class="col-6 align-self-center">
      <div class= "item-image">
        <% if @item.image.attached? %>
          <%= cl_image_tag(@item.image.key, class:"show-image") %>
        <% else %>
          <div class="d-flex justify-content-center alert alert-info">Something went wrong, your photo will be displayed soon</div>
          <%= image_tag "nomadarte_logo.png", alt: "Photo placeholder" %>
        <% end %>
      </div>
    </div>
    <div class="col"></div>
    <div class="col-4 align-self-center">
      <div class="item-info">
        <h1><%= @item.name %> by <%= @item.artist %></h1>
        <hr>
        <p><%= @item.description %></p>
        <p><strong><%= humanized_money_with_symbol @item.price_per_day %></strong>/day</p>
        <p><%= @item.category_name %></p>
        <p><i>Owned by <%= @item.user.username %></i></p>
      </div>
      <div class="col-12 mt-3 book-form">
        <fieldset>
          <%= simple_form_for [@item, @booking] do |f| %>
            <%= f.input :start_date, as: :date, order: [:day, :month, :year] %>
            <%= f.input :end_date, as: :date, order: [:day, :month, :year] %>
            <%= f.button :submit, "Rent now!", class: "primary-btn full-width-btn" %>
          <% end %>
        </fieldset>
      </div>
    </div>
    <div class="col align-self-start">
      <button type="button" class="btn btn-outline-secondary" id="heart-button">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
          <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
        </svg>
      </button>
    </div>
  </div>
</div>
<script>
  const btn = document.getElementById("heart-button")
  console.log(btn)
  btn.addEventListener('click', (e) => {
  btn.classList.toggle('heart-button')
     })
</script>
<%# <%= link_to "Back to index", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NomadArte</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render 'shared/navbar' %>
    <div class=<%= "container" unless current_page?(root_path) %> >
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="carouselExample" class="carousel slide carousel-size-box ">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'https://sothebys-com.brightspotcdn.com/dims4/default/657041f/2147483647/strip/true/crop/4800x2283+0+659/resize/1440x685!/format/webp/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fdotcom%2F2b%2F4c%2F49d9ec5949e5945a74765e591595%2Fn11248-cmhl9-t1-rx-01-2.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption">
        <div class="transform-h1 pt-5">
          <h1 class="home-title">NOMAD</h1>
          <h1 class="home-title2 text-end">ARTE</h1>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'https://sothebys-com.brightspotcdn.com/dims4/default/c82f23f/2147483647/strip/true/crop/3090x1470+0+1426/resize/1440x685!/format/webp/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fdotcom%2Fe8%2Fa4%2Fd6cb1c1e40d388e0d7c94048504a%2Fwillem-de-kooning-untitled.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption">
         <div class="transform-h1 pt-5">
          <h1 class="home-title">NOMAD</h1>
          <h1 class="home-title2 text-end">ARTE</h1>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'https://sothebys-com.brightspotcdn.com/dims4/default/9bded50/2147483647/strip/true/crop/2880x1370+0+0/resize/1440x685!/format/webp/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fdotcom%2Ff5%2F6d%2Fdd4103144911ab681207b871aab2%2Fprivate-sales-website-banners-b-2880x1370.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption">
        <div class="transform-h1 pt-5">
          <h1 class="home-title">NOMAD</h1>
          <h1 class="home-title2 text-end">ARTE</h1>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/payments/new.html.erb
<div class="row justify-content-center">
  <div class="col-xl-5">
    <div class="card p-5">
      <div class="mb-1 d-flex flex-column justify-content-center">
        <h1>Checkout summary</h1>
        <hr>
        <div class="align-self-center">
          <h6>
            <strong><%= @booking.item.name %></strong> <%= @booking.item.description %>
            <br>
            <br>
            Price per day: <%= humanized_money_with_symbol @booking.item.price_per_day%>
          </h6>
        </div>
      </div>
      <div> <%= cl_image_tag(@booking.item.image.key, class: "show-image p-4") %></div>
      <h6 class="text-center">Total price: <strong><%= humanized_money_with_symbol @booking.total_price%></strong></h6>
      <button id="pay" class="primary-btn">Checkout</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @booking.stripe_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<article id="wrap">
	<article id="lightings">
    	<section id="one">
            <section id="two">
                <section id="three">
                    <section id="four">
                        <section id="five">

                        </section>
                    </section>
                </section>
            </section>
		</section>
    </article>
</article>
<div class="footer-container">
  <footer class="text-center text-light pt-3 footer-background pt-5 card-footer" >
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <h6>About Us</h6>
          <p>The NomadArte team revolutionizes the art world by effortlessly connecting artists and art enthusiasts, making the process of renting and letting a breeze.</p>
        </div>
        <div class="col-lg-4">
          <h6>Contact</h6>
          <p>Email: info@nomadarte.com <br>
          Phone: +1 123-456-7890</p>
        </div>
        <div class="col-lg-4">
          <h6>Follow Us</h6>
          <ul class="list-inline">
            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook text-white"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter text-white"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-instagram text-white"></i></a></li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-12 text-center">
          <p>&copy; 2023 NomadArte. All rights reserved.</p>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid d-flex justify-content-between">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("nomadarte_logo.png") %>
    <% end %>
    <div class="input-group">
      <%= form_tag(items_path, method: :get, class: "d-flex mx-auto") do %>
        <div class="search-field">
          <%= button_tag(type: "submit", class: "btn", id: "search-btn" ) do %>
            Search
          <% end %>
          <%= text_field_tag(:query, nil, class: "btn", id: "search-input", placeholder: "Rent your art") %>
        </div>
      <% end %>
    </div>
    <button class="navbar-toggler" type: "button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="d-flex">
            <%= link_to "Browse catalog", items_path, id: "browse-btn" %>
          </li>
          <li class="d-flex">
            <%= link_to "Upload new item", new_item_path, id: "upload-btn" %>
          </li>
          <li class="dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "pdiakjeemou4s9c1386jl5janddl-Circle.webp", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Settings", "/dasboard/settings", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, id: "inlog-btn" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, id: "signup-btn" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>